export const NULL = null;

export const SET_ID_TOKEN = 'SET_ID_TOKEN'
export const SET_AUTHORIZATION_CODE = 'SET_AUTHORIZATION_CODE'

export const EXCHANGING_AUTHORIZATION_CODE = 'EXCHANGING_AUTHORIZATION_CODE'
export const EXCHANGED_AUTHORIZATION_CODE = 'EXCHANGED_AUTHORIZATION_CODE'

export const EXCHANGING_REFRESH_TOKEN = 'EXCHANGING_REFRESH_TOKEN'
export const EXCHANGED_REFRESH_TOKEN = 'EXCHANGED_REFRESH_TOKEN'

export const LOGOUT = 'LOGOUT'

export const READY_TO_CONNECT = 'READY_TO_CONNECT'
export const CONNECTED = 'CONNECTED'

export const RESOURCES_RETRIEVED = 'RESOURCES_RETRIEVED'

export const CONFIGURE_COMPONENTS = 'CONFIGURE_COMPONENTS'
export const INSTANCES_COMPONENTS_DISTRIBUTED = 'INSTANCES_COMPONENTS_DISTRIBUTED'

export const SET_BOARD = 'SET_BOARD'

export const ADD_NOTE = 'ADD_NOTE'
export const REMOVE_NOTE = 'REMOVE_NOTE'
export const UPDATE_NOTE = 'UPDATE_NOTE'
export const SELECT_NOTE = 'SELECT_NOTE'
